### ISSUE TITLE
Update lab.rb and lab.js to reflect README prompts

### ISSUE THREAD

**Issue by laurenfazah** [ga-wdi-boston/ruby-vs-js-arrays#13]
Labs were reordered, `lab.js` and `lab.rb` should reflect. Q4 of lab 1 is modified on README, but not reflected on `lab.rb`

**Comment by neugierige** [comment]
updates were made in the new [ruby-array](https://github.com/ga-wdi-boston/ruby-arrays) repo

ok to close?
