### ISSUE TITLE
Add linter configurations for comparison to JS

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/ruby-vs-js-arrays#2]
Some developers are experiencing ES6 warnings from JSHint. To fix:
1.  `git remote add js-template git@github.com:ga-wdi-boston/js-template`
2.  `git fetch js-template`
3.  `git checkout js-template/master -- .jshintrc .jshintignore .jscsrc`

**Comment by laurenfazah** [comment]
fixed if you'd like to close @jrhorn424
