### ISSUE TITLE
Second lab requires results from first lab

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/ruby-vs-js-arrays#3]
Second lab requires results from first lab, please note.

**Comment by neugierige** [comment]
Noted. Could I just give them that array\* to work with, after a designated amount of time for part 1 has passed? 

that array = `[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]`

**Comment by gaand** [comment]
Isn't the first lab in `bin/lab.rb` now the bonus at the end of the talk?

I think that we need more files or some other separation of these two pieces.

**Comment by neugierige** [comment]
I see. In that case, are the developers expected to simply create an array (of lenth >= 5) with which to complete lab 2?

**Comment by gaand** [comment]
@neugierige I think this repo needs to be refactored to account for the accumulated cruft. I'm happy to continue to respond to issues but I'm not sure that's sufficient at this point.  But, that's up to you.

**Comment by gaand** [comment]
Subsumed by change to ruby-array
