### ISSUE TITLE
Lab 2 #4 doesn't make sense

### ISSUE THREAD

**Issue by laurenfazah** [ga-wdi-boston/ruby-vs-js-arrays#9]
Should be reworked.

**Comment by jrhorn424** [comment]
Is there anything specific?

**Comment by berziiii** [comment]
Yes, I agree after giving this material. I thought I knew what the question was asking but then during lab, there was a lot of misunderstanding. 

Does it mean that you're passing the array `[-12, -49]` into the 5th element of an array AND the next 2 elements. 

OR

Does it mean you're passing the array `[-12, -49]` to the 5th element from the end of the array, which has a total length of 3.

**Comment by gaand** [comment]
``` ruby
ary = [1, 2, 3, 4, 5, 6] # => [1, 2, 3, 4, 5, 6]
ary[5, 3] = [12, 24] # => [12, 24]
ary# => [1, 2, 3, 4, 5, 12, 24]
```

This seems quite informative to me.

**Comment by laurenfazah** [comment]
I still don't think wording is clear given the `for a length of 3` bit. 

For 013, I've changed from

>   Assign `[-12, -49]` to the 5th element from the end for a length of 3.

to

>   Assign `[-12, -49]` to the 5th element from the end.

**Comment by gaand** [comment]
@laurenfazah Please revert this change.  The point is that the operation follows:

``` ruby
ary = (1..6).to_a #=> [1, 2, 3, 4, 5, 6]
ary[3, 3] = [10, 20] #=> [10, 20]
ary #=> [1, 2, 3, 10, 20]
```

Three elements of the array are replaced by two elements.

**Comment by neugierige** [comment]
I'm a bit confused by the conundrum over question 4 in lab #2 which states, "Assign `[-12, -49]` to the 5th element from the end." Because there is currently no solution for lab #2 (I plan to create one), please verify whether this is what we want the developers to do: 

```
my_array = (1..6).to_a #=> [1, 2, 3, 4, 5, 6]
my_array[-5] = [-12, -49] #=> [1, [-12, -49], 3, 4, 5, 6]

my_other_array = (1..3).to_a #=> [1, 2, 3]
my_other_array[-5] = [-12, -49] #=> nil
```

Please note that immediately prior to this lab, there is a demo that shows that you cannot have a negative index number that goes past index 0.

**Comment by gaand** [comment]
The point is to illustrate that in ruby you can replace a subset of elements of one length, with a set of a different length and that the length of the array is changed as shown i https://github.com/ga-wdi-boston/ruby-vs-js-arrays/issues/9#issuecomment-243002525

**Comment by neugierige** [comment]
Understood. I would like to verify that the code for `my_array` (from my previous comment) is a reasonable solution for question  4, which states, "Assign [-12, -49] to the 5th element from the end." Or are you expecting `my_array` to be updated to `[1, -12, -49, 3, 4, 5, 6]` instead?

**Comment by gaand** [comment]
Neither.

This is the intent:

``` sh
[1] pry(main)> my_array = (1..6).to_a
=> [1, 2, 3, 4, 5, 6]
[2] pry(main)> my_array[-5, 3] = [-12, -49]
=> [-12, -49]
[3] pry(main)> my_array
=> [1, -12, -49, 5, 6]
[4] pry(main)> 
```

So the array gets shorter by one, the number 4 is removed, and 2 and 3 are replaced.

**Comment by neugierige** [comment]
Ok. Could we update the question prompt so as to reflect that intent more clearly? The current wording of the question... 

> Assign `[-12, -49]` to the 5th element from the end.

...does not say anything about the length parameter. It would not be reasonable to expect developers to produce this code...

`my_array[-5, 3] = [-12, -49]`

...based upon this wording of the question, as there is no way to know that one should also modify a specific range within the array, let alone a range of 3. I propose that the language to be updated as follows:

> Assign `[-12, -49]` to the range starting from the 5th element from the end, for a length of 3.

**Comment by gaand** [comment]
@neugierige I'm good with this wording change.  Please include it in the lab.
